    - name: Template KubeletConfig
      when: core_user_pass is defined
      ansible.builtin.template:
        src: "kubeletconfig.yaml.j2"
        dest: "{{ generated_asset_path }}/{{ cluster_name }}/openshift/kubeletconfig-{{ item.0 }}.yaml"
        mode: '0644'
      with_nested:
      - "{{ ['master', 'worker'] }}"
      - "{{ kubelet_config }}"