- name: Template Core user password
  when: core_user_pass is defined
  ansible.builtin.template:
    src: "core-user.bu_{{ item }}.j2"
    dest: "{{ generated_asset_path }}/{{ cluster_name }}/openshift/core-user_{{ item }}.bu"
    mode: '0644'
  with_items:
  - master
  - worker

- name: Template Core user password MachineConfig
  when: core_user_pass is defined
  ansible.builtin.shell:
    cmd: |
      {{ generated_asset_path }}/../../bin/butane \
      {{ generated_asset_path }}/{{ cluster_name }}/openshift/core-user_{{ item }}.bu > {{ generated_asset_path }}/{{ cluster_name }}/openshift/core-user_{{ item }}.yaml
  with_items:
  - master
  - worker